/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David Mamujee
 * Date: December 21, 2012
 * Description: A program that will help user learn to calculate geometric shapes
 */
import java.text.*;
import javax.swing.ButtonGroup;
public class geometricCalculator extends javax.swing.JFrame {

    /**
     * Creates new form geometricCalculator
     */    
    //Initializes global variables to be used throughout program
    private static 
           double a,b,c,d,e;
           int i = 0,z,y,dim1,dim2,dim3,dim,values,questions = 0,correct = 0,circ = 0;           
           //Creates array for all of the shapes
           String[] shapes = {"Square/Rectangle","Circle","Triangle","Cube","Sphere","Square-based Pyramid","Parellogram","Trapezoid","Cone","Cylinder","Triangular Prism"};
           DecimalFormat x = new DecimalFormat ("#,###,###,##0.##");
           
    public geometricCalculator() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePage = new javax.swing.JInternalFrame();
        homeToCalculatorButton = new javax.swing.JButton();
        homeToFormulasButton = new javax.swing.JButton();
        homeToTestButton = new javax.swing.JButton();
        welcomeTitle = new javax.swing.JLabel();
        instructionsLine1 = new javax.swing.JLabel();
        instructionsLine3 = new javax.swing.JLabel();
        instructionsLine2 = new javax.swing.JLabel();
        intructionsLine4 = new javax.swing.JLabel();
        intructionsLine5 = new javax.swing.JLabel();
        formulasPage = new javax.swing.JInternalFrame();
        twoDemShapeTitle = new javax.swing.JLabel();
        areaTitle = new javax.swing.JLabel();
        perimeterTitle = new javax.swing.JLabel();
        shapeTitle = new javax.swing.JLabel();
        squareLabel = new javax.swing.JLabel();
        squareAreaLabel = new javax.swing.JLabel();
        squarePerimeterLabel = new javax.swing.JLabel();
        circleLabel = new javax.swing.JLabel();
        circleAreaLabel = new javax.swing.JLabel();
        circlePerimeterLabel = new javax.swing.JLabel();
        triangleLabel = new javax.swing.JLabel();
        trianglePerimeterLabel = new javax.swing.JLabel();
        triangleAreaLabel = new javax.swing.JLabel();
        parallelogramLabel = new javax.swing.JLabel();
        parallelogramPerimeterLabel = new javax.swing.JLabel();
        parallelogramAreaLabel = new javax.swing.JLabel();
        trapezoidLabel = new javax.swing.JLabel();
        trapezoidPerimeterLabel = new javax.swing.JLabel();
        trapezoidAreaLabel = new javax.swing.JLabel();
        threeDemShapeLabel = new javax.swing.JLabel();
        shape1Title = new javax.swing.JLabel();
        surfaceAreaTitle = new javax.swing.JLabel();
        volumeTitle = new javax.swing.JLabel();
        cubeLabel = new javax.swing.JLabel();
        cubcSurfaceLabel = new javax.swing.JLabel();
        cubeVolumeLabel = new javax.swing.JLabel();
        sphereLabel = new javax.swing.JLabel();
        sphereSurfaceLabel = new javax.swing.JLabel();
        sphereVolumeLabel = new javax.swing.JLabel();
        pyramidLabel = new javax.swing.JLabel();
        pyramidSurfaceLabel = new javax.swing.JLabel();
        pyramidVolumeLabel = new javax.swing.JLabel();
        coneLabel = new javax.swing.JLabel();
        coneSurfaceLabel = new javax.swing.JLabel();
        coneVolumeLabel = new javax.swing.JLabel();
        cylinderLabel = new javax.swing.JLabel();
        cylinderSurfaceLabel = new javax.swing.JLabel();
        cylinderVolumeLabel = new javax.swing.JLabel();
        prismLabel = new javax.swing.JLabel();
        prismSurfaceLabel = new javax.swing.JLabel();
        prismVolumeLabel = new javax.swing.JLabel();
        formulasToHomeButton = new javax.swing.JButton();
        formulasToCalculatorButton = new javax.swing.JButton();
        formulasToTestButton = new javax.swing.JButton();
        formulasTitle = new javax.swing.JLabel();
        testPage = new javax.swing.JInternalFrame();
        testToHomeButton = new javax.swing.JButton();
        testToCalculatorButton = new javax.swing.JButton();
        testToFormulasButton = new javax.swing.JButton();
        piIrrational = new javax.swing.JRadioButton();
        pi314 = new javax.swing.JRadioButton();
        square1Button = new javax.swing.JButton();
        circle1Button = new javax.swing.JButton();
        parallelogram1Button = new javax.swing.JButton();
        trapezoid1Button = new javax.swing.JButton();
        cube1Button = new javax.swing.JButton();
        sphere1Button = new javax.swing.JButton();
        pyramid1Button = new javax.swing.JButton();
        cone1Button = new javax.swing.JButton();
        cylinder1Button = new javax.swing.JButton();
        triangle1Button = new javax.swing.JButton();
        prism1Button = new javax.swing.JButton();
        dimension1 = new javax.swing.JLabel();
        dimension2 = new javax.swing.JLabel();
        dimension3 = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        dim1Output = new javax.swing.JLabel();
        dim2Output = new javax.swing.JLabel();
        dim3Output = new javax.swing.JLabel();
        dimension = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        quizTitleLabel = new javax.swing.JLabel();
        decimalNote1 = new javax.swing.JLabel();
        quizIntrusctionsLabel1 = new javax.swing.JLabel();
        quizIntrusctionsLabel2 = new javax.swing.JLabel();
        quizIntrusctionsLabel3 = new javax.swing.JLabel();
        quizIntrusctionsLabel4 = new javax.swing.JLabel();
        quizIntrusctionsLabel5 = new javax.swing.JLabel();
        quizIntrusctionsLabel6 = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        calculatorPage = new javax.swing.JInternalFrame();
        areaButton = new javax.swing.JButton();
        dimension5Input = new javax.swing.JTextField();
        calculationTitleLabel = new javax.swing.JLabel();
        perimeterButton = new javax.swing.JButton();
        dimension2Input = new javax.swing.JTextField();
        dimension3Input = new javax.swing.JTextField();
        dimension1Input = new javax.swing.JTextField();
        parellelogramButton = new javax.swing.JButton();
        trapezoidButton = new javax.swing.JButton();
        coneButton = new javax.swing.JButton();
        cylinderButton = new javax.swing.JButton();
        prismButton = new javax.swing.JButton();
        twoDemTitleLabel = new javax.swing.JLabel();
        threeDemTitleLabel = new javax.swing.JLabel();
        titelLabel = new javax.swing.JLabel();
        circleButton = new javax.swing.JButton();
        squareRectangleButton = new javax.swing.JButton();
        cubeButton = new javax.swing.JButton();
        pyramidButton = new javax.swing.JButton();
        sphereButton = new javax.swing.JButton();
        dimension4Input = new javax.swing.JTextField();
        triangleButton = new javax.swing.JButton();
        dimensionsTitleLabel = new javax.swing.JLabel();
        volumeButton = new javax.swing.JButton();
        surfaceAreaButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        dimension1Label = new javax.swing.JLabel();
        dimension2Label = new javax.swing.JLabel();
        dimension3Label = new javax.swing.JLabel();
        dimension4Label = new javax.swing.JLabel();
        dimension5Label = new javax.swing.JLabel();
        calculatorToHomeButton = new javax.swing.JButton();
        calculatorToFormulasButton = new javax.swing.JButton();
        calculatorToTestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(725, 675));

        homePage.setMinimumSize(new java.awt.Dimension(100, 100));
        homePage.setVisible(true);
        homePage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeToCalculatorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeToCalculatorButton.setText("Go to Calculator");
        homeToCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToCalculatorButtonActionPerformed(evt);
            }
        });
        homePage.getContentPane().add(homeToCalculatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        homeToFormulasButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeToFormulasButton.setText("Go to Formulas");
        homeToFormulasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToFormulasButtonActionPerformed(evt);
            }
        });
        homePage.getContentPane().add(homeToFormulasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, -1));

        homeToTestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeToTestButton.setText("Go to Test");
        homeToTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeToTestButtonActionPerformed(evt);
            }
        });
        homePage.getContentPane().add(homeToTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 109, -1));

        welcomeTitle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        welcomeTitle.setText("Welcome to the Geometric Calculator! ");
        homePage.getContentPane().add(welcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));

        instructionsLine1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionsLine1.setText("This program will help you calculate the perimeter, area, surface area, and volume of");
        homePage.getContentPane().add(instructionsLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        instructionsLine3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionsLine3.setText(" geometric shape, different geometric shapes. There are three different elements to this");
        homePage.getContentPane().add(instructionsLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        instructionsLine2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionsLine2.setText("geometric shapes. There are the formulas, which show the user how to calculate each");
        homePage.getContentPane().add(instructionsLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        intructionsLine4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intructionsLine4.setText(" program. There is the calculator which you can use to check there answers with, there is a ");
        homePage.getContentPane().add(intructionsLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        intructionsLine5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intructionsLine5.setText("formula sheet and there is a quiz to test your knowledge of calculating geomteric shapes.");
        homePage.getContentPane().add(intructionsLine5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        formulasPage.setPreferredSize(new java.awt.Dimension(750, 437));
        formulasPage.setVisible(false);
        formulasPage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        twoDemShapeTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        twoDemShapeTitle.setText("2-Dimensional Shapes");
        formulasPage.getContentPane().add(twoDemShapeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 27, -1, -1));

        areaTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        areaTitle.setText("Area");
        formulasPage.getContentPane().add(areaTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 58, -1, -1));

        perimeterTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        perimeterTitle.setText("Perimeter");
        formulasPage.getContentPane().add(perimeterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 58, -1, -1));

        shapeTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shapeTitle.setText("Shape");
        formulasPage.getContentPane().add(shapeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        squareLabel.setText("Rectangle");
        formulasPage.getContentPane().add(squareLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        squareAreaLabel.setText("Length x Width");
        formulasPage.getContentPane().add(squareAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 81, -1, -1));

        squarePerimeterLabel.setText("2 x (Length+Width)");
        formulasPage.getContentPane().add(squarePerimeterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 81, -1, -1));

        circleLabel.setText("Circle");
        formulasPage.getContentPane().add(circleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        circleAreaLabel.setText("Pi x Radius x Radius");
        formulasPage.getContentPane().add(circleAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 101, -1, -1));

        circlePerimeterLabel.setText("2 x Pi x Radius");
        formulasPage.getContentPane().add(circlePerimeterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 101, -1, -1));

        triangleLabel.setText("Triangle");
        formulasPage.getContentPane().add(triangleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        trianglePerimeterLabel.setText("Base + Side1 + Side2");
        formulasPage.getContentPane().add(trianglePerimeterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 121, -1, -1));

        triangleAreaLabel.setText("1/2 x Base x Height");
        formulasPage.getContentPane().add(triangleAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 121, -1, -1));

        parallelogramLabel.setText("Parallelogram");
        formulasPage.getContentPane().add(parallelogramLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        parallelogramPerimeterLabel.setText("2 x (Side + Base)");
        formulasPage.getContentPane().add(parallelogramPerimeterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 141, -1, -1));

        parallelogramAreaLabel.setText("Base x Height");
        formulasPage.getContentPane().add(parallelogramAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 141, -1, -1));

        trapezoidLabel.setText("Trapezoid");
        formulasPage.getContentPane().add(trapezoidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        trapezoidPerimeterLabel.setText("Top + Bottom + Side1 + Side2");
        formulasPage.getContentPane().add(trapezoidPerimeterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 161, -1, -1));

        trapezoidAreaLabel.setText("(Top + Bottom)/2 x Height");
        formulasPage.getContentPane().add(trapezoidAreaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 161, -1, -1));

        threeDemShapeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        threeDemShapeLabel.setText("3-Dimensional Shapes");
        formulasPage.getContentPane().add(threeDemShapeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 193, -1, -1));

        shape1Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shape1Title.setText("Shape");
        formulasPage.getContentPane().add(shape1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, -1));

        surfaceAreaTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        surfaceAreaTitle.setText("Surface Area");
        formulasPage.getContentPane().add(surfaceAreaTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 219, -1, -1));

        volumeTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volumeTitle.setText("Volume");
        formulasPage.getContentPane().add(volumeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 219, -1, -1));

        cubeLabel.setText("Cube");
        formulasPage.getContentPane().add(cubeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        cubcSurfaceLabel.setText("2(LengthxWidth)+ 2(LengthxHeight)+2(WidthxHeight)");
        formulasPage.getContentPane().add(cubcSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 242, -1, -1));

        cubeVolumeLabel.setText("Length x Width x Height");
        formulasPage.getContentPane().add(cubeVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 242, -1, -1));

        sphereLabel.setText("Sphere");
        formulasPage.getContentPane().add(sphereLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        sphereSurfaceLabel.setText("4 x Pi x Radius x Radius");
        formulasPage.getContentPane().add(sphereSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 262, -1, -1));

        sphereVolumeLabel.setText("4/3 x Pi x Radius x Radius x Radius");
        formulasPage.getContentPane().add(sphereVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 262, -1, -1));

        pyramidLabel.setText("Pyramid");
        formulasPage.getContentPane().add(pyramidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, -1));

        pyramidSurfaceLabel.setText("Base x Base + 2 x (Base x Side Height)");
        formulasPage.getContentPane().add(pyramidSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 282, -1, -1));

        pyramidVolumeLabel.setText("1/3 x Base x Height");
        formulasPage.getContentPane().add(pyramidVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 282, -1, -1));

        coneLabel.setText("Cone");
        formulasPage.getContentPane().add(coneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, -1, -1));

        coneSurfaceLabel.setText("Pi x Radius x Radius + Pi x Radius x √(Radius^2 + Height^2) ");
        formulasPage.getContentPane().add(coneSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 302, -1, -1));

        coneVolumeLabel.setText("1/3 x Pi x Radius x Radius x Height");
        formulasPage.getContentPane().add(coneVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 302, -1, -1));

        cylinderLabel.setText("Cylinder");
        formulasPage.getContentPane().add(cylinderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 322, -1, -1));

        cylinderSurfaceLabel.setText("2 x Pi x Radius x Radius + 2 x Pi x Radius x Height");
        formulasPage.getContentPane().add(cylinderSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 322, -1, -1));

        cylinderVolumeLabel.setText("Pi x Radius x Radius x Height");
        formulasPage.getContentPane().add(cylinderVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 322, -1, -1));

        prismLabel.setText("Triangle Prism");
        formulasPage.getContentPane().add(prismLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 342, -1, -1));

        prismSurfaceLabel.setText("(Base x Height)+(Base x Length)+(Side1 x Length)+(Side2 x Length)");
        formulasPage.getContentPane().add(prismSurfaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 342, -1, -1));

        prismVolumeLabel.setText("1/2 x Base x Height x Length");
        formulasPage.getContentPane().add(prismVolumeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 342, -1, -1));

        formulasToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formulasToHomeButton.setText("Home");
        formulasToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulasToHomeButtonActionPerformed(evt);
            }
        });
        formulasPage.getContentPane().add(formulasToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        formulasToCalculatorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formulasToCalculatorButton.setText("Calculator");
        formulasToCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulasToCalculatorButtonActionPerformed(evt);
            }
        });
        formulasPage.getContentPane().add(formulasToCalculatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        formulasToTestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formulasToTestButton.setText("Test");
        formulasToTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulasToTestButtonActionPerformed(evt);
            }
        });
        formulasPage.getContentPane().add(formulasToTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        formulasTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        formulasTitle.setText("Formulas");
        formulasPage.getContentPane().add(formulasTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        testPage.setMinimumSize(new java.awt.Dimension(450, 750));
        testPage.setPreferredSize(new java.awt.Dimension(450, 850));
        testPage.setVisible(false);
        testPage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        testToHomeButton.setText("Home");
        testToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testToHomeButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(testToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        testToCalculatorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        testToCalculatorButton.setText("Calculator");
        testToCalculatorButton.setEnabled(false);
        testToCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testToCalculatorButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(testToCalculatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        testToFormulasButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        testToFormulasButton.setText("Formulas");
        testToFormulasButton.setEnabled(false);
        testToFormulasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testToFormulasButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(testToFormulasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        piIrrational.setSelected(true);
        piIrrational.setText("pi = irrational");
        testPage.getContentPane().add(piIrrational, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        pi314.setText("pi = 3.14");
        testPage.getContentPane().add(pi314, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        square1Button.setText("Square/Rectangle");
        square1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(square1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        circle1Button.setText("Circle");
        circle1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circle1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(circle1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, -1));

        parallelogram1Button.setText("Parallelogram");
        parallelogram1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parallelogram1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(parallelogram1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, -1));

        trapezoid1Button.setText("Trapezoid");
        trapezoid1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapezoid1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(trapezoid1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));

        cube1Button.setText("Cube");
        cube1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cube1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(cube1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, -1));

        sphere1Button.setText("Sphere");
        sphere1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphere1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(sphere1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 90, -1));

        pyramid1Button.setText("Pyramid");
        pyramid1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramid1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(pyramid1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 90, -1));

        cone1Button.setText("Cone");
        cone1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cone1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(cone1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, -1));

        cylinder1Button.setText("Cylinder");
        cylinder1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylinder1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(cylinder1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, -1));

        triangle1Button.setText("Triangle");
        triangle1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangle1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(triangle1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, -1));

        prism1Button.setText("Prism");
        prism1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prism1ButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(prism1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, -1));
        testPage.getContentPane().add(dimension1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        testPage.getContentPane().add(dimension2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        testPage.getContentPane().add(dimension3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        userInput.setText("0");
        testPage.getContentPane().add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 140, -1));

        enterButton.setText("Enter");
        enterButton.setEnabled(false);
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        generateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generateButton.setText("Generate");
        generateButton.setEnabled(false);
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
        testPage.getContentPane().add(dim1Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 20, -1));
        testPage.getContentPane().add(dim2Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));
        testPage.getContentPane().add(dim3Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));
        testPage.getContentPane().add(dimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 250, 20));
        testPage.getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 290, 20));

        quizTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        quizTitleLabel.setText("Quiz");
        testPage.getContentPane().add(quizTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        decimalNote1.setText("Note: Please enter decimals to two decimal places");
        testPage.getContentPane().add(decimalNote1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        quizIntrusctionsLabel1.setText("Welcome to the the Quiz! To begin the quiz, choose a shape, then hit the ");
        testPage.getContentPane().add(quizIntrusctionsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        quizIntrusctionsLabel2.setText("the Generate button. This will bring up the dimension for the shape you");
        testPage.getContentPane().add(quizIntrusctionsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        quizIntrusctionsLabel3.setText("chose. Throughout the quiz, you can changes shapes. Then enter your");
        testPage.getContentPane().add(quizIntrusctionsLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        quizIntrusctionsLabel4.setText(" answer into the text box. After completing a minimum of 5 questions, you can");
        testPage.getContentPane().add(quizIntrusctionsLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        quizIntrusctionsLabel5.setText(" hit the finish button to see your score. While in the test, you cannot leave");
        testPage.getContentPane().add(quizIntrusctionsLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        quizIntrusctionsLabel6.setText("this page. You can also choose for pi to be an irrational number or 3.14.");
        testPage.getContentPane().add(quizIntrusctionsLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        testPage.getContentPane().add(finishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        calculatorPage.setVisible(false);
        calculatorPage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaButton.setText("Area");
        areaButton.setEnabled(false);
        areaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(areaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 473, 95, -1));

        dimension5Input.setText("0");
        dimension5Input.setEnabled(false);
        calculatorPage.getContentPane().add(dimension5Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 415, 220, -1));

        calculationTitleLabel.setText("Choose Calculation:");
        calculatorPage.getContentPane().add(calculationTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 453, -1, -1));

        perimeterButton.setText("Perimeter");
        perimeterButton.setEnabled(false);
        perimeterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimeterButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(perimeterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 473, 110, -1));

        dimension2Input.setText("0");
        dimension2Input.setEnabled(false);
        calculatorPage.getContentPane().add(dimension2Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 337, 220, -1));

        dimension3Input.setText("0");
        dimension3Input.setEnabled(false);
        calculatorPage.getContentPane().add(dimension3Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 363, 220, -1));

        dimension1Input.setText("0");
        dimension1Input.setEnabled(false);
        calculatorPage.getContentPane().add(dimension1Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 311, 220, -1));

        parellelogramButton.setText("Parallelogram");
        parellelogramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parellelogramButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(parellelogramButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 119, -1));

        trapezoidButton.setText("Trapezoid");
        trapezoidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapezoidButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(trapezoidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, 119, -1));

        coneButton.setText("Cone");
        coneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coneButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(coneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 187, 160, -1));

        cylinderButton.setText("Cylinder");
        cylinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylinderButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(cylinderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 216, 160, -1));

        prismButton.setText("Triangular Prism");
        prismButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(prismButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 245, 160, -1));

        twoDemTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        twoDemTitleLabel.setText("2-Dimensional Shapes");
        calculatorPage.getContentPane().add(twoDemTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        threeDemTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        threeDemTitleLabel.setText("3-Dimensional Shapes");
        calculatorPage.getContentPane().add(threeDemTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        titelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titelLabel.setText("Geometric Calculator");
        calculatorPage.getContentPane().add(titelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 11, -1, -1));

        circleButton.setText("Circle");
        circleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(circleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 119, -1));

        squareRectangleButton.setText("Square/Rectangle");
        squareRectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRectangleButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(squareRectangleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cubeButton.setText("Cube");
        cubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(cubeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 100, 160, -1));

        pyramidButton.setText("Square-based Pyramid");
        pyramidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramidButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(pyramidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 158, 160, -1));

        sphereButton.setText("Sphere");
        sphereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphereButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(sphereButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 129, 160, -1));

        dimension4Input.setText("0");
        dimension4Input.setEnabled(false);
        calculatorPage.getContentPane().add(dimension4Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 389, 220, -1));

        triangleButton.setText("Triangle");
        triangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(triangleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 119, -1));

        dimensionsTitleLabel.setText("Enter Dimensions:");
        calculatorPage.getContentPane().add(dimensionsTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 286, -1, -1));

        volumeButton.setText("Volume");
        volumeButton.setEnabled(false);
        volumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(volumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 507, 95, -1));

        surfaceAreaButton.setText("Surface Area");
        surfaceAreaButton.setEnabled(false);
        surfaceAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfaceAreaButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(surfaceAreaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 507, 110, -1));

        outputLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculatorPage.getContentPane().add(outputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 295, 21));
        calculatorPage.getContentPane().add(dimension1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, -1, -1));
        calculatorPage.getContentPane().add(dimension2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, -1, -1));
        calculatorPage.getContentPane().add(dimension3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, -1, -1));
        calculatorPage.getContentPane().add(dimension4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 389, -1, -1));
        calculatorPage.getContentPane().add(dimension5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, -1, 14));

        calculatorToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculatorToHomeButton.setText("Home");
        calculatorToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorToHomeButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(calculatorToHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        calculatorToFormulasButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculatorToFormulasButton.setText("Formulas");
        calculatorToFormulasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorToFormulasButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(calculatorToFormulasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        calculatorToTestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculatorToTestButton.setText("Test");
        calculatorToTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorToTestButtonActionPerformed(evt);
            }
        });
        calculatorPage.getContentPane().add(calculatorToTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formulasPage, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculatorPage, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePage, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulasPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculatorPage, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(testPage, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void squareRectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRectangleButtonActionPerformed
        reset();
        unlock2dem();
        dimensionTitle();
        //Sets dimension labels to appropriate label for shape
        dimension1Label.setText("Length:");
        dimension2Label.setText("Width:");
        //Sets to variable for shape for use in array
        i = 0;        
    }//GEN-LAST:event_squareRectangleButtonActionPerformed

    private void circleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleButtonActionPerformed
        reset();
        unlock2dem();        
        dimension2Input.setEnabled(false);
        dimension1Label.setText("Radius:");
        perimeterButton.setText("Circumference");
        //Variable so that perimeter changes to circumferance
        circ = 1;
        i = 1;
        dimensionTitle();        
    }//GEN-LAST:event_circleButtonActionPerformed

    private void triangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleButtonActionPerformed
        reset();
        unlock2dem();        
        dimension3Input.setEnabled(true);
        dimension4Input.setEnabled(true);
        dimension1Label.setText("Base:");
        dimension2Label.setText("Height:");
        dimension3Label.setText("Side 1:");
        dimension4Label.setText("Side 2:");        
        i = 2;
        dimensionTitle();        
    }//GEN-LAST:event_triangleButtonActionPerformed

    private void cubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeButtonActionPerformed
        reset();
        unlock3dem();        
        dimension1Label.setText("Length:");
        dimension2Label.setText("Width:");
        dimension3Label.setText("Height:");
        i = 3;
        dimensionTitle();        
    }//GEN-LAST:event_cubeButtonActionPerformed

    private void sphereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphereButtonActionPerformed
        reset();
        unlock3dem();        
        dimension2Input.setEnabled(false);
        dimension3Input.setEnabled(false);
        dimension1Label.setText("Radius:");
        i = 4;
        dimensionTitle();       
    }//GEN-LAST:event_sphereButtonActionPerformed

    private void pyramidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramidButtonActionPerformed
        reset();
        unlock3dem();        
        dimension1Label.setText("Base Length:");
        dimension2Label.setText("Height of Side:");
        dimension3Label.setText("Height:");
        i = 5;
        dimensionTitle();        
    }//GEN-LAST:event_pyramidButtonActionPerformed

    private void perimeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimeterButtonActionPerformed
        double output;        
        //Retrieves answer from method
        output = perimeterretrieve(i);
        //If shape is circle, circumference is used in output as well as answer
        if (circ == 1){
            outputLabel.setText("The circuference is " + x.format(output));
        }
        else {
            outputLabel.setText("The perimeter is " + x.format(output));
        }       
    }//GEN-LAST:event_perimeterButtonActionPerformed

    private void areaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaButtonActionPerformed
        double output;
        //Retrieves answer from method
        output = arearetrieve(i);        
        //Output answer
        outputLabel.setText("The area is " + x.format(output));
    }//GEN-LAST:event_areaButtonActionPerformed

    private void surfaceAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfaceAreaButtonActionPerformed
        double output;
        output = perimeterretrieve(i);
        outputLabel.setText("The surface area is " + x.format(output));
    }//GEN-LAST:event_surfaceAreaButtonActionPerformed

    private void volumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeButtonActionPerformed
        double output;
        output = arearetrieve(i);
        outputLabel.setText("The volume is " + x.format(output));
    }//GEN-LAST:event_volumeButtonActionPerformed

    private void parellelogramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parellelogramButtonActionPerformed
        reset();
        unlock2dem();        
        dimension3Input.setEnabled(true);
        dimension1Label.setText("Base Length:");
        dimension2Label.setText("Side Length:");
        dimension3Label.setText("Height:");
        i = 6;
        dimensionTitle();        
    }//GEN-LAST:event_parellelogramButtonActionPerformed

    private void trapezoidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapezoidButtonActionPerformed
        reset();
        unlock2dem();        
        dimension3Input.setEnabled(true);
        dimension4Input.setEnabled(true);
        dimension5Input.setEnabled(true);
        dimension1Label.setText("Top Length:");
        dimension2Label.setText("Bottom Length:");
        dimension3Label.setText("Height:");
        dimension4Label.setText("Side 1 Length:");
        dimension5Label.setText("Side 2 Length:");        
        i = 7;
        dimensionTitle();        
    }//GEN-LAST:event_trapezoidButtonActionPerformed

    private void coneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coneButtonActionPerformed
        reset();
        unlock3dem();        
        dimension3Input.setEnabled(false);
        dimension1Label.setText("Radius:");
        dimension2Label.setText("Height:");        
        i = 8;
        dimensionTitle();        
    }//GEN-LAST:event_coneButtonActionPerformed

    private void cylinderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylinderButtonActionPerformed
        reset();
        unlock3dem();        
        dimension3Input.setEnabled(false);
        dimension1Label.setText("Radius:");
        dimension2Label.setText("Height:");        
        i = 9;
        dimensionTitle();        
    }//GEN-LAST:event_cylinderButtonActionPerformed

    private void prismButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismButtonActionPerformed
        reset();
        unlock3dem();        
        dimension4Input.setEnabled(true);
        dimension5Input.setEnabled(true);
        dimension1Label.setText("Base:");
        dimension2Label.setText("Height:");
        dimension3Label.setText("Length:");
        dimension4Label.setText("Side Length 1:");
        dimension5Label.setText("Side Length 2:");        
        i = 10;
        dimensionTitle();        
    }//GEN-LAST:event_prismButtonActionPerformed

    private void homeToCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToCalculatorButtonActionPerformed
        //Page that is being left is hidden and page that is going to is set to visible
        homePage.setVisible(false);
        calculatorPage.setVisible(true);
    }//GEN-LAST:event_homeToCalculatorButtonActionPerformed

    private void calculatorToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorToHomeButtonActionPerformed
        calculatorPage.setVisible(false);
        homePage.setVisible(true);
    }//GEN-LAST:event_calculatorToHomeButtonActionPerformed

    private void formulasToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulasToHomeButtonActionPerformed
        formulasPage.setVisible(false);
        homePage.setVisible(true);
    }//GEN-LAST:event_formulasToHomeButtonActionPerformed

    private void formulasToCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulasToCalculatorButtonActionPerformed
        formulasPage.setVisible(false);
        calculatorPage.setVisible(true);
    }//GEN-LAST:event_formulasToCalculatorButtonActionPerformed

    private void formulasToTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulasToTestButtonActionPerformed
        formulasPage.setVisible(false);
        testPage.setVisible(true);
        //Locks Calculator and Formulas button so that while in test user cannot cheat
        testToCalculatorButton.setEnabled(false);        
        testToFormulasButton.setEnabled(false);
        testReset();
        testVariableReset();
    }//GEN-LAST:event_formulasToTestButtonActionPerformed

    private void homeToFormulasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToFormulasButtonActionPerformed
        homePage.setVisible(false);
        formulasPage.setVisible(true);
    }//GEN-LAST:event_homeToFormulasButtonActionPerformed

    private void homeToTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeToTestButtonActionPerformed
        homePage.setVisible(false);
        testPage.setVisible(true);
        testToCalculatorButton.setEnabled(false);        
        testToFormulasButton.setEnabled(false);
        testReset();
        testVariableReset();
    }//GEN-LAST:event_homeToTestButtonActionPerformed

    private void testToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testToHomeButtonActionPerformed
        testPage.setVisible(false);
        homePage.setVisible(true);
    }//GEN-LAST:event_testToHomeButtonActionPerformed

    private void testToCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testToCalculatorButtonActionPerformed
        testPage.setVisible(false);
        calculatorPage.setVisible(true);
    }//GEN-LAST:event_testToCalculatorButtonActionPerformed

    private void testToFormulasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testToFormulasButtonActionPerformed
        testPage.setVisible(false);
        formulasPage.setVisible(true);
    }//GEN-LAST:event_testToFormulasButtonActionPerformed

    private void calculatorToFormulasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorToFormulasButtonActionPerformed
        calculatorPage.setVisible(false);
        formulasPage.setVisible(true);
    }//GEN-LAST:event_calculatorToFormulasButtonActionPerformed

    private void calculatorToTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorToTestButtonActionPerformed
        calculatorPage.setVisible(false);
        testPage.setVisible(true);
        testToCalculatorButton.setEnabled(false);        
        testToFormulasButton.setEnabled(false);
        testReset();
        testVariableReset();
    }//GEN-LAST:event_calculatorToTestButtonActionPerformed

    private void square1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        //Number used to access formula in array
        z = 0;
        //Dimension labels are set for that shape
        dimension1.setText("Length:");
        dimension2.setText("Width:");
        //Variable is used so that program knows how many dimension to generate
        values = 2;
        dim = 2;
    }//GEN-LAST:event_square1ButtonActionPerformed

    private void circle1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circle1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 1;
        dimension1.setText("Radius:");
        values = 1;
        dim = 2;
    }//GEN-LAST:event_circle1ButtonActionPerformed

    private void triangle1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangle1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 2;
        dimension1.setText("Base:");
        dimension2.setText("Height:");
        values = 2;
        dim = 2;
    }//GEN-LAST:event_triangle1ButtonActionPerformed

    private void parallelogram1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parallelogram1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 6;
        dimension1.setText("Base:");
        dimension2.setText("Height:");
        values = 2;
        dim = 2;
    }//GEN-LAST:event_parallelogram1ButtonActionPerformed

    private void trapezoid1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapezoid1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 7;
        dimension1.setText("Base:");
        dimension2.setText("Top:");
        dimension3.setText("Height:");
        values = 3;
        dim = 2;
    }//GEN-LAST:event_trapezoid1ButtonActionPerformed

    private void cube1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cube1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 3;
        dimension1.setText("Base:");
        dimension2.setText("Width:");
        dimension3.setText("Height:");
        values = 3;
        dim = 3;        
    }//GEN-LAST:event_cube1ButtonActionPerformed

    private void sphere1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphere1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 4;
        dimension1.setText("Radius:");
        values = 1;
        dim = 3;
    }//GEN-LAST:event_sphere1ButtonActionPerformed

    private void pyramid1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramid1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 5;
        dimension1.setText("Base:");
        dimension2.setText("Height:");
        values = 2;
        dim = 3;
    }//GEN-LAST:event_pyramid1ButtonActionPerformed

    private void cone1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cone1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 8;
        dimension1.setText("Radius:");
        dimension2.setText("Height:");
        values = 2;
        dim = 3;
    }//GEN-LAST:event_cone1ButtonActionPerformed

    private void cylinder1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylinder1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 9;        
        dimension1.setText("Radius");
        dimension2.setText("Height:");
        values = 2;
        dim = 3;
    }//GEN-LAST:event_cylinder1ButtonActionPerformed

    private void prism1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prism1ButtonActionPerformed
        testReset();
        generateButton.setEnabled(true);
        z = 10;
        dimension1.setText("Base:");
        dimension2.setText("Height");
        dimension3.setText("Length");
        values = 3;
        dim = 3;
    }//GEN-LAST:event_prism1ButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        dimensionTest();        
        enterButton.setEnabled(true);
        testToCalculatorButton.setEnabled(false);
        testToFormulasButton.setEnabled(false);
        output.setText("");
        userInput.setText("0");
        //Generates number between 2 and 15 depending how many dimensions there are and outputs it
        switch(values)
        {
            case 1:
                dim1 = (int)(Math.random()*14 + 2);
                dim1Output.setText(dim1+"");
                break;                
            case 2:
              dim1 = (int)(Math.random()*14 + 2);
              dim2 = (int)(Math.random()*14 + 2);
              dim1Output.setText(dim1+"");
              dim2Output.setText(dim2+"");
              break;
            case 3:
               dim1 = (int)(Math.random()*14 + 2);
               dim2 = (int)(Math.random()*14 + 2);
               dim3 = (int)(Math.random()*14 + 2);
               dim1Output.setText(dim1+"");
               dim2Output.setText(dim2+"");
               dim3Output.setText(dim3+"");
               break;
            default:
                dim1Output.setText("Error");                
        }        
    }//GEN-LAST:event_generateButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        double answer, formattedAnswer, userAnswer,pi = Math.PI;        
        //Counter for how many question have been answers goes up by one
        questions++;
        enterButton.setEnabled(false);
        //Unlocks finish button of at least 5 question have been answered
        if (questions >= 5){
            finishButton.setEnabled(true);
        }
        a = dim1;
        b = dim2;
        c = dim3;
        //Allows user to choose if pi equals irrational number or 3.14
        if (piIrrational.isSelected() == true){
            pi = Math.PI;
        }
        if (pi314.isSelected() == true){
            pi = 3.14;
        }     
        //Creates area array and calculates shape
        double[] areaformulas = {a*b,pi*a*a,0.5*a*b,a*b*c,1.33333*pi*a*a*a,0.33333*a*a*c,a*c,(a+b)*c*0.5,0.33333*pi*a*a*b,pi*a*a*b,0.5*a*b*c};
        answer = areaformulas [z];
        //Retreives user answer
        userAnswer = Double.parseDouble(userInput.getText());
        //Rounds answer to two decimal places
        formattedAnswer = Double.valueOf(x.format(answer));
        //Outputs answer is correct is user answer is within 0.01 of correct answer
        if (userAnswer == formattedAnswer||userAnswer+0.01 == formattedAnswer||userAnswer-0.01 == formattedAnswer){
            output.setText("Correct!");
            //Counter counting how many question user gets correct
            correct++;
        }
        else if (userAnswer != formattedAnswer){
            output.setText("Incorrect!");
        }       
    }//GEN-LAST:event_enterButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        //Unlocks buttons to other pages
        testToCalculatorButton.setEnabled(true);
        testToHomeButton.setEnabled(true);
        testToFormulasButton.setEnabled(true);
        finishButton.setEnabled(true);
        //Outputs score to user
        output.setText("You got "+ correct +" right out of "+ questions +" questions.");
        //Resets test variables
        correct = 0;
        questions = 0;
    }//GEN-LAST:event_finishButtonActionPerformed

    //Resets calculator
    private void reset(){
        //Locks dimension inputs
        dimension1Input.setEnabled(false);
        dimension2Input.setEnabled(false);
        dimension3Input.setEnabled(false);
        dimension4Input.setEnabled(false);
        dimension5Input.setEnabled(false);
        //Locks calculation buttons
        perimeterButton.setEnabled(false);
        areaButton.setEnabled(false);
        volumeButton.setEnabled(false);
        surfaceAreaButton.setEnabled(false);
        //Sets dimension labels to blank
        dimension1Label.setText("");
        dimension2Label.setText("");
        dimension3Label.setText("");
        dimension4Label.setText("");
        dimension5Label.setText("");
        //Sets dimension inputs to 0
        dimension1Input.setText("0");
        dimension2Input.setText("0");
        dimension3Input.setText("0");
        dimension4Input.setText("0");
        dimension5Input.setText("0");
        perimeterButton.setText("Perimeter");
        //Sets output label to blank
        outputLabel.setText("");       
        circ = 0;
    }
    
    private void unlock2dem(){
        //Unlocks two dimensional shape calculation buttons and inputs usually used by two dimensional shapes
        perimeterButton.setEnabled(true);
        areaButton.setEnabled(true);
        dimension1Input.setEnabled(true);
        dimension2Input.setEnabled(true);
    }
    
    private void unlock3dem(){
        //Unlocks three dimensional shape calculation buttonsinputs usually used by three dimensional shapes
        volumeButton.setEnabled(true);
        surfaceAreaButton.setEnabled(true);
        dimension1Input.setEnabled(true);
        dimension2Input.setEnabled(true);
        dimension3Input.setEnabled(true);        
    }    
    //Method for calculating perimeter   
    private double perimeterretrieve(int i){
        double value;
        //Retrieves user input an assign them to variables
        a = Double.parseDouble(dimension1Input.getText());
        b = Double.parseDouble(dimension2Input.getText());
        c = Double.parseDouble(dimension3Input.getText());
        d = Double.parseDouble(dimension4Input.getText());
        e = Double.parseDouble(dimension5Input.getText());
        //Array with each formula to calculate perimter
        double[] perimeterformulas = {2*(a+b),2*Math.PI*a,a+c+d,(2*a*c)+(2*a*d)+(2*c*d),4*Math.PI*a*a,2*a*b+a*a,2*(a+b),a+b+d+e,Math.PI*a*(Math.sqrt(a*a+b*b))+Math.PI*a*a,2*Math.PI*a*a+2*Math.PI*a*b,a*c+d*c+e*c+b*a};
        //Calculates the perimeter of shape by using array and returns the value
        value = perimeterformulas[i];
        return value;
    }
    //Method for calculating area
    private double arearetrieve(int i){
        double value;
        //Retrieves user input an assign them to variables
        a = Double.parseDouble(dimension1Input.getText());
        b = Double.parseDouble(dimension2Input.getText());
        c = Double.parseDouble(dimension3Input.getText());
        d = Double.parseDouble(dimension4Input.getText());
        e = Double.parseDouble(dimension5Input.getText());
        //Array with each formula to calculate area
        double[] areaformulas = {a*b,Math.PI*a*a,0.5*a*b,a*b*c,1.33333*Math.PI*a*a*a,0.33333*a*a*c,a*c,(a+b)*c*0.5,0.33333*Math.PI*a*a*b,Math.PI*a*a*b,0.5*a*b*c};
        //Calculates the area of shapes by using array and returns the value
        value = areaformulas[i];
        return value;
    }    
    //Method to group buttons as a button group
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup( );        
        bg1.add(piIrrational);
        bg1.add(pi314);        
    }
    //Method to reset test
    private void testReset() {
        //Reset text of dimension to blank
        dimension1.setText("");
        dimension2.setText("");
        dimension3.setText("");
        dim1Output.setText("");
        dim2Output.setText("");
        dim3Output.setText("");
        dimension.setText("");
    }
    //Resets test variables
    private void testVariableReset(){
        questions = 0;
        correct = 0;
    }
    //Method for dimension output
    private void dimensionTitle(){
        dimensionsTitleLabel.setText("Enter Dimensions for " + shapes[i] + ":");
    }
    //Method for output if dimension is 2 or 3 dimensional
    private void dimensionTest(){
        if (dim == 2){
            dimension.setText("Enter Area for " + shapes[z]);
        }
        if (dim == 3){
            dimension.setText("Enter Volume for " + shapes[z]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(geometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(geometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(geometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(geometricCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new geometricCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaButton;
    private javax.swing.JLabel areaTitle;
    private javax.swing.JLabel calculationTitleLabel;
    private javax.swing.JInternalFrame calculatorPage;
    private javax.swing.JButton calculatorToFormulasButton;
    private javax.swing.JButton calculatorToHomeButton;
    private javax.swing.JButton calculatorToTestButton;
    private javax.swing.JButton circle1Button;
    private javax.swing.JLabel circleAreaLabel;
    private javax.swing.JButton circleButton;
    private javax.swing.JLabel circleLabel;
    private javax.swing.JLabel circlePerimeterLabel;
    private javax.swing.JButton cone1Button;
    private javax.swing.JButton coneButton;
    private javax.swing.JLabel coneLabel;
    private javax.swing.JLabel coneSurfaceLabel;
    private javax.swing.JLabel coneVolumeLabel;
    private javax.swing.JLabel cubcSurfaceLabel;
    private javax.swing.JButton cube1Button;
    private javax.swing.JButton cubeButton;
    private javax.swing.JLabel cubeLabel;
    private javax.swing.JLabel cubeVolumeLabel;
    private javax.swing.JButton cylinder1Button;
    private javax.swing.JButton cylinderButton;
    private javax.swing.JLabel cylinderLabel;
    private javax.swing.JLabel cylinderSurfaceLabel;
    private javax.swing.JLabel cylinderVolumeLabel;
    private javax.swing.JLabel decimalNote1;
    private javax.swing.JLabel dim1Output;
    private javax.swing.JLabel dim2Output;
    private javax.swing.JLabel dim3Output;
    private javax.swing.JLabel dimension;
    private javax.swing.JLabel dimension1;
    private javax.swing.JTextField dimension1Input;
    private javax.swing.JLabel dimension1Label;
    private javax.swing.JLabel dimension2;
    private javax.swing.JTextField dimension2Input;
    private javax.swing.JLabel dimension2Label;
    private javax.swing.JLabel dimension3;
    private javax.swing.JTextField dimension3Input;
    private javax.swing.JLabel dimension3Label;
    private javax.swing.JTextField dimension4Input;
    private javax.swing.JLabel dimension4Label;
    private javax.swing.JTextField dimension5Input;
    private javax.swing.JLabel dimension5Label;
    private javax.swing.JLabel dimensionsTitleLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JInternalFrame formulasPage;
    private javax.swing.JLabel formulasTitle;
    private javax.swing.JButton formulasToCalculatorButton;
    private javax.swing.JButton formulasToHomeButton;
    private javax.swing.JButton formulasToTestButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JInternalFrame homePage;
    private javax.swing.JButton homeToCalculatorButton;
    private javax.swing.JButton homeToFormulasButton;
    private javax.swing.JButton homeToTestButton;
    private javax.swing.JLabel instructionsLine1;
    private javax.swing.JLabel instructionsLine2;
    private javax.swing.JLabel instructionsLine3;
    private javax.swing.JLabel intructionsLine4;
    private javax.swing.JLabel intructionsLine5;
    private javax.swing.JLabel output;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton parallelogram1Button;
    private javax.swing.JLabel parallelogramAreaLabel;
    private javax.swing.JLabel parallelogramLabel;
    private javax.swing.JLabel parallelogramPerimeterLabel;
    private javax.swing.JButton parellelogramButton;
    private javax.swing.JButton perimeterButton;
    private javax.swing.JLabel perimeterTitle;
    private javax.swing.JRadioButton pi314;
    private javax.swing.JRadioButton piIrrational;
    private javax.swing.JButton prism1Button;
    private javax.swing.JButton prismButton;
    private javax.swing.JLabel prismLabel;
    private javax.swing.JLabel prismSurfaceLabel;
    private javax.swing.JLabel prismVolumeLabel;
    private javax.swing.JButton pyramid1Button;
    private javax.swing.JButton pyramidButton;
    private javax.swing.JLabel pyramidLabel;
    private javax.swing.JLabel pyramidSurfaceLabel;
    private javax.swing.JLabel pyramidVolumeLabel;
    private javax.swing.JLabel quizIntrusctionsLabel1;
    private javax.swing.JLabel quizIntrusctionsLabel2;
    private javax.swing.JLabel quizIntrusctionsLabel3;
    private javax.swing.JLabel quizIntrusctionsLabel4;
    private javax.swing.JLabel quizIntrusctionsLabel5;
    private javax.swing.JLabel quizIntrusctionsLabel6;
    private javax.swing.JLabel quizTitleLabel;
    private javax.swing.JLabel shape1Title;
    private javax.swing.JLabel shapeTitle;
    private javax.swing.JButton sphere1Button;
    private javax.swing.JButton sphereButton;
    private javax.swing.JLabel sphereLabel;
    private javax.swing.JLabel sphereSurfaceLabel;
    private javax.swing.JLabel sphereVolumeLabel;
    private javax.swing.JButton square1Button;
    private javax.swing.JLabel squareAreaLabel;
    private javax.swing.JLabel squareLabel;
    private javax.swing.JLabel squarePerimeterLabel;
    private javax.swing.JButton squareRectangleButton;
    private javax.swing.JButton surfaceAreaButton;
    private javax.swing.JLabel surfaceAreaTitle;
    private javax.swing.JInternalFrame testPage;
    private javax.swing.JButton testToCalculatorButton;
    private javax.swing.JButton testToFormulasButton;
    private javax.swing.JButton testToHomeButton;
    private javax.swing.JLabel threeDemShapeLabel;
    private javax.swing.JLabel threeDemTitleLabel;
    private javax.swing.JLabel titelLabel;
    private javax.swing.JButton trapezoid1Button;
    private javax.swing.JLabel trapezoidAreaLabel;
    private javax.swing.JButton trapezoidButton;
    private javax.swing.JLabel trapezoidLabel;
    private javax.swing.JLabel trapezoidPerimeterLabel;
    private javax.swing.JButton triangle1Button;
    private javax.swing.JLabel triangleAreaLabel;
    private javax.swing.JButton triangleButton;
    private javax.swing.JLabel triangleLabel;
    private javax.swing.JLabel trianglePerimeterLabel;
    private javax.swing.JLabel twoDemShapeTitle;
    private javax.swing.JLabel twoDemTitleLabel;
    private javax.swing.JTextField userInput;
    private javax.swing.JButton volumeButton;
    private javax.swing.JLabel volumeTitle;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables
}
